name: CI Sobel

on:
  push:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libsdl2-dev libsdl2-ttf-dev

      - name: Créer les fichiers dat factices
        run: |
          mkdir -p dat
          touch dat/ShakeNDry_1920x1080_120fps_420_8bit_YUV.yuv
          touch dat/DejaVuSans.ttf

      - name: Configurer avec CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Compiler
        run: cmake --build build --config Release
